version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/motivation-backend:${IMAGE_TAG}
    environment:
      - DEBUG=False
      - DATABASE_URL=/app/db.sqlite3
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "8000:8000"

  frontend:
    image: ${DOCKER_USERNAME}/motivation-frontend:${IMAGE_TAG}
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./ssl/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/nginx/privkey.pem:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

volumes:
