#!/bin/bash
echo "🎯 Demo: Admin Approval & Publish"
echo "=================================="
echo ""
echo "📝 Step 1: User submits a story"
echo "   → Story status: PENDING"
echo "   → Not visible on homepage"
echo ""
echo "👨‍💼 Step 2: Admin reviews in Pending Approvals tab"
echo "   → Click story to preview"
echo "   → Read content"
echo "   → Watch video if present"
echo ""
echo "✅ Step 3: Admin clicks 'Approve & Publish'"
echo "   → Story status: APPROVED"
echo "   → is_active: TRUE"
echo "   → Published instantly!"
echo ""
echo "🎉 Step 4: Story appears in Stories feed"
echo "   → All students can now see it"
echo "   → Full formatting and videos visible"
echo ""
echo "🌐 Try it now:"
echo "   1. Go to: http://localhost:3000/create-story"
echo "   2. Sign in as admin"
echo "   3. Click 'Pending Approvals' tab"
echo "   4. Click 'Approve & Publish' on any story"
echo ""
