# Generated by Django 4.2.7 on 2025-09-28 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('NEWS', 'News'), ('JOKES', 'Jokes'), ('QUOTATION', 'Quotation'), ('STORY', 'Story')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('target_grade', models.IntegerField(blank=True, help_text='Target grade (1-12)', null=True)),
                ('target_school', models.CharField(blank=True, help_text='Target school', max_length=255, null=True)),
                ('source', models.CharField(choices=[('openai', 'OpenAI'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(help_text='SHA-256 hash for deduplication', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'db_table': 'content',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['section', 'published_at'], name='content_section_274ad1_idx'), models.Index(fields=['target_grade', 'section'], name='content_target__1f98cb_idx'), models.Index(fields=['target_school', 'section'], name='content_target__c35138_idx'), models.Index(fields=['hash'], name='content_hash_2aae72_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmarks',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
