# Generated by Django 4.2.7 on 2025-10-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_content_created_by_content_rich_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Approval status for user-submitted content', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the content was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this content', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('admin', 'Admin'), ('user', 'User Submitted')], default='admin', max_length=20),
        ),
    ]
