# Generated by Django 4.2.7 on 2025-10-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_approval_status_content_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='original_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='content.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if content was rejected', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='resubmission_status',
            field=models.CharField(choices=[('none', 'Not Resubmitted'), ('resubmitted', 'Resubmitted'), ('original', 'Original Version')], default='none', max_length=20),
        ),
    ]
