# Generated by Django 4.2.7 on 2025-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_original_submission_content_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_section_274ad1_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_target__1f98cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_target__c35138_idx',
        ),
        migrations.RemoveField(
            model_name='content',
            name='section',
        ),
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('MOTIVATION', 'Motivation'), ('JOKES', 'Jokes'), ('QUOTATION', 'Quotation'), ('PUZZLE', 'Puzzle')], default='MOTIVATION', max_length=20),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'published_at'], name='content_content_504675_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['target_grade', 'content_type'], name='content_target__83a102_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['target_school', 'content_type'], name='content_target__ff115a_idx'),
        ),
    ]
