# Generated by Django 4.2.7 on 2025-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='news_url',
            field=models.URLField(blank=True, help_text='News article URL', null=True),
        ),
    ]
