# Generated by Django 4.2.7 on 2025-10-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('MOTIVATION', 'Motivation'), ('JOKES', 'Jokes'), ('QUOTATION', 'Quotation'), ('PUZZLE', 'Puzzle'), ('TONGUE_TWISTER', 'Tongue Twister')], default='MOTIVATION', max_length=20),
        ),
    ]
